/// Embedded secrets for distribution builds.
/// This file is generated by CI or created manually for local development.
/// DO NOT commit real values to git.
enum Secrets {
    /// Socket Mode app-level token (xapp-...)
    static let slackAppToken = ""

    /// OAuth client ID (from Slack App → Basic Information)
    static let slackClientId = ""

    /// OAuth client secret (from Slack App → Basic Information)
    static let slackClientSecret = ""
}
